server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.105.96.239:3306/part_time_monarch?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 662662
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    password: tidc662662
    port: 25
    protocol: smtp
    username: 18934086807@163.com


mybatis:
  type-aliases-package: com.tidc.parttimemonarch.dao
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.onepro.custom.mapper: DEBUG
