server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://39.105.96.239:3306/part_time_monarch?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 662662
mybatis:
  type-aliases-package: com.tidc.parttimemonarch.dao
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.onepro.custom.mapper: DEBUG
#logging:
#  level: debug
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
