server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.105.96.239:3306/part_time_monarch?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 662662
  jackson:
    default-property-inclusion: non_null
  redis:
    database: 0
    host:

    port: 6379
    password: 662662
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1


mybatis:
  type-aliases-package: com.tidc.parttimemonarch.dao
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.onepro.custom.mapper: DEBUG
