server:
  port: 8080
spring:
  datasource:
    url: ENC(ghVcWtQpdChG04TZzdSsPUgimEXB6EeUO00bpwd0YAQI22HfDrktcUQMyC6Fx7jWEa8puw2ChFyk3d+ZH6AIDZC7PA7QMV5L)
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(syF66GGc1bKx+aneat1NBg==)
    password: ENC(9ly9TeF57UcW3/VbNT0+0g==)
  redis:
    database: 0
    host: ENC(zTw5I00nNHfRr9TxgOrTYyoxs3wydBVW)
    password: ENC(9ly9TeF57UcW3/VbNT0+0g==)
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: ENC(8KhM8z/JN0sNaeQMlkEnh+ExvjSe3XmH6lsIVxwqyZQ=)
    port: 587
    protocol: smtp
    username: ENC(L8QQkZ9KsRvEPLY3t52t2SMTWndR1IkGULAiSFuULt4=)
  jackson:
    default-property-inclusion: non_null
  session:
    store-type: redis
    timeout: 30s
    redis:
      namespace: session


mybatis:
  type-aliases-package: com.tidc.parttimemonarch.dao
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.onepro.custom.mapper: DEBUG

swagger:
  show: true

email:
  util:
    username: ENC(L8QQkZ9KsRvEPLY3t52t2SMTWndR1IkGULAiSFuULt4=)


jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7